name: Build & Test
on:
  push:
    branches:
      - prod
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: view/.node-version
          cache-dependency-path: view/package-lock.json
          cache: 'npm'

      - name: Install dependencies
        run: cd view && npm install

      - name: Run tests
        run: cd view && npm test

  deploy:
    needs: build
    name: Deploy
    if: github.ref == 'refs/heads/prod'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit