name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        description: Cloudflare Api Token
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: view/.node-version
          cache-dependency-path: view/package-lock.json
          cache: 'npm'

      - name: Install dependencies
        run: cd view && npm install

      - name: Build
        run: cd view && npm run build

      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler pages prod view/build