name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        description: Cloudflare Api Token
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "view"